services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./sql_data:/var/lib/mysql
      - ./sql_data/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
    - 9100:9100
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    ports:
      - 9104:9104
    command:
      - '--config.my-cnf=/etc/mysql_exporter/.my.cnf'
      - '--mysqld.address=mysql.josuecarames.com:3306'
    volumes:
      - ./.my.cnf:/etc/mysql_exporter/.my.cnf